### ISSUE TITLE
[Bug] ListDirectory appears to fail when current working directory is drive root

### ISSUE THREAD

**Issue by rasta-mouse** [cobbr/Covenant#156]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
`ls` seems to fail when the current working directory is set to the drive root.

**To Reproduce**
1. `cd C:\`
2. `ls`

**Expected behavior**
Get directory output.

```
(rasta) > pwd

C:\

(rasta) > ls

System.ArgumentException: Path cannot be the empty string or all whitespace.
Parameter name: path2
   at System.IO.Path.InternalCombine(String path1, String path2)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at SharpSploit.Enumeration.Host.GetDirectoryListing(String Path)
   at Task.Execute(String Path)

(rasta) > ls C:\

Name                               Length       CreationTimeUtc      LastAccessTimeUtc    LastWriteTimeUtc
----                               ------       ---------------      -----------------    ----------------
C:\$GetCurrent                     0            17/06/2019 18:17:32  18/06/2019 18:52:36  18/06/2019 18:52:36
C:\$Recycle.Bin                    0            11/04/2018 23:38:20  09/05/2019 17:53:44  09/05/2019 17:53:44
```

**Comment by cobbr** [comment]
@rasta-mouse I can't seem to reproduce this. I'm not sure what the issue was or how it was fixed, but are you able to verify this is working for you now?

**Comment by rasta-mouse** [comment]
@cobbr still appears to be the case for me.

```
[19/06/2020 19:53:27 UTC] ChangeDirectory completed

(rasta) > cd C:\

C:\

[19/06/2020 19:53:47 UTC] GetCurrentDirectory completed

(rasta) > pwd

C:\

[19/06/2020 19:54:05 UTC] ListDirectory completed

(rasta) > ls

System.ArgumentException: Path cannot be the empty string or all whitespace.
Parameter name: path2
   at System.IO.Path.InternalCombine(String path1, String path2)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at SharpSploit.Enumeration.Host.GetDirectoryListing(String Path)
   at Task.Execute(String Path)
```

**Comment by cobbr** [comment]
@rasta-mouse What's the OS Version of the target system?

**Comment by cobbr** [comment]
Ping @rasta-mouse

**Comment by rasta-mouse** [comment]
Sorry @cobbr.  My test system is Windows 10 Enterprise LTSC (1809).
