### ISSUE TITLE
Operation returned an invalid status code 'BadRequest'

### ISSUE THREAD

**Issue by Comanio00** [cobbr/Covenant#17]
Hey.

During the execution of commands, an error appears in Elite:

(Covenant: Grunts\69fc1b9cfa) > getsystem
[!] EliteMenu Exception: Operation returned an invalid status code 'BadRequest'
   at Covenant.API.CovenantAPI.ApiGruntsByIdTaskingsPostWithHttpMessagesAsync(Int32 id, GruntTasking gruntTasking, Dictionary`2 customHeaders, CancellationToken can
cellationToken) in /app/API/CovenantAPI.cs:line 6690
   at Covenant.API.CovenantAPIExtensions.ApiGruntsByIdTaskingsPostAsync(ICovenantAPI operations, Int32 id, GruntTasking gruntTasking, CancellationToken cancellation
Token) in /app/API/CovenantAPIExtensions.cs:line 1283
   at Covenant.API.CovenantAPIExtensions.ApiGruntsByIdTaskingsPost(ICovenantAPI operations, Int32 id, GruntTasking gruntTasking) in /app/API/CovenantAPIExtensions.c
s:line 1268
   at Elite.Menu.Tasks.MenuCommandTaskStart.Command(MenuItem menuItem, String UserInput) in /app/Menu/Tasks/TaskMenuItem.cs:line 89
   at Elite.Menu.Grunts.MenuCommandGruntInteractGetSystem.Command(MenuItem menuItem, String UserInput) in /app/Menu/Grunts/InteractGruntMenuItem.cs:line 1300
   at Elite.Menu.EliteMenu.PrintMenu(String UserInput) in /app/Menu/EliteMenu.cs:line 122
(Covenant: Grunts\69fc1b9cfa) > powershell get-process
[!] EliteMenu Exception: Object reference not set to an instance of an object.
   at Elite.Menu.Grunts.MenuCommandGruntInteractPowerShell.Command(MenuItem menuItem, String UserInput) in /app/Menu/Grunts/InteractGruntMenuItem.cs:line 602
   at Elite.Menu.EliteMenu.PrintMenu(String UserInput) in /app/Menu/EliteMenu.cs:line 122

Covenant Error:

Task Compilation failed: CompilationErrors:
(7,16): error CS0246: The type or namespace name 'Tokens' could not be found (are you missing a using directive or an assembly reference?)
(7,31): error CS0246: The type or namespace name 'Tokens' could not be found (are you missing a using directive or an assembly reference?)
   at Covenant.Core.Compiler.Compile(CompilationRequest request)
   at Covenant.Models.Grunts.GruntTasking.Compile(String TaskCode, List`1 Parameters, List`1 ReferenceAssemblies, List`1 ReferenceSourceLibraries, List`1 EmbeddedResources, DotNetVersion dotNetFrameworkVersion) in /app/Models/Grunts/GruntTasking.cs:line 115
   at Covenant.Controllers.GruntTaskingController.CreateGruntTasking(Int32 id, GruntTasking gruntTasking) in /app/Controllers/GruntTaskingController.cs:line 171

After restarting Covenant, the error disappears.
After sending several commands, the error appears again.
What is not configured?

**Comment by cobbr** [comment]
Verified as a bug, not sure what's going on here, but I'll look into it

**Comment by cobbr** [comment]
The `GetSystem` task wasn't setup to reference SharpSploit. Should be fixed now in acc1d99de30c2765a243cee1f8e1a5717307d095

Unfortunately, you're still going to run into #18. There's an issue with threading and token manipulation right now.
