### ISSUE TITLE
[Problem] Listener Status

### ISSUE THREAD

**Issue by kake123qw** [cobbr/Covenant#202]
Hi.
When i want to create a listener in covenant c2, it was created successfully. 
Unfortunately, the status of it set to "uninitialized". How can i run listener successfully? or change status of it to running?
Please guide me about this issue.
Thanks.

**Comment by juliourena** [comment]
Maybe you are trying to listen on a port that is already in use, try a different port.

If that doesn't work make sure your settings for BindPort/BindAddress are correct.

**Comment by kake123qw** [comment]
No. 
i tried it by port number 80 or port number 443. So, i started listening. After that, in launcher section is empty and i can't choose any of the listeners which i created before. So, i can't continue launching any payload in covenant.
please , help me in listening and launching process of covenant.

**Comment by rasta-mouse** [comment]
Are you running Covenant as root / admin?

**Comment by Vanilla03304** [comment]
Hi all, 
have similar error, when I try to create a new listener, it is created in stopped state and throws me an error:

2020-07-03 14:01:31.5595||FATAL|Microsoft.AspNetCore.Server.Kestrel|Unable to start Kestrel. System.Net.Sockets.SocketException (99): Cannot assign requested address                                               
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)                                                                                                 
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)                                                                
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()                                                                                          
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)                                                                         
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)                                                                                       
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)                        
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)  

The docker is running as root on Kali Linux. I tried different IPs and ports, tried rebooting the VM. The screenshot of listener config is also attached. Has anyone. managed to fix it? 

![image](https://user-images.githubusercontent.com/67793807/86477434-19bc6880-bd51-11ea-823b-ee49d2f7e912.png)

**Comment by cobbr** [comment]
@Vanilla03304 It look to me like you are probably trying to use a BindAddress that does not exist within the Docker container. Keep in mind that you must choose a BindAddress available within the container. Usually, it almost always makes sense to keep the BindAddress as `0.0.0.0`

**Comment by cobbr** [comment]
@kake123qw This can happen if you forget to run Covenant as sudo/root/Administrator. I would try to stop Covenant and run it with administrative privileges.

**Comment by cobbr** [comment]
Closing due to lack of response. Let me know if the issue persists and we can re-open.
