### ISSUE TITLE
[Bug] Spawing a grunt with stored proxy credentials eventually breaks the C2 server

### ISSUE THREAD

**Issue by m4rvxpn** [cobbr/Covenant#240]
**Bug**
Bug

**Bug description**
When spawning an http grunt with stored proxy credentials gets successful. Whereas while continuing with the usage the c2 server breaks and we need to restart.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a custom HTTP template using stored credentials 
2. Generate a launcher (binary, Powershell, etc.) using the template created
3. Spawn a Grunt executing the payload
3. See error while operating a while and the server breaks

**Expected behaviour**
The server should not break.

**Screenshots**
 
![image](https://user-images.githubusercontent.com/16485430/92674894-e80ce280-f33b-11ea-9bb0-beed8532e29b.png)

***
Assembly /assemblyname:"GruntHttpProxy " /parameters:""
Loop Exception: System.Net.WebException The remote server returned an error: (502) Bad Gateway.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GruntExecutor.HttpMessenger.Read()
   at GruntExecutor.TaskingMessenger.ReadTaskingMessage()
   at GruntExecutor.Grunt.Execute(String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
Loop Exception: System.Net.WebException The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GruntExecutor.HttpMessenger.Read()
   at GruntExecutor.TaskingMessenger.ReadTaskingMessage()
   at GruntExecutor.Grunt.Execute(String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
Loop Exception: System.Net.WebException The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GruntExecutor.HttpMessenger.Read()
   at GruntExecutor.TaskingMessenger.ReadTaskingMessage()
   at GruntExecutor.Grunt.Execute(String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
Loop Exception: System.Net.WebException The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GruntExecutor.HttpMessenger.Read()
   at GruntExecutor.TaskingMessenger.ReadTaskingMessage()
   at GruntExecutor.Grunt.Execute(String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
Loop Exception: System.Net.WebException The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GruntExecutor.HttpMessenger.Read()
   at GruntExecutor.TaskingMessenger.ReadTaskingMessage()
   at GruntExecutor.Grunt.Execute(String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
Loop Exception: System.Net.WebException The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GruntExecutor.HttpMessenger.Read()
   at GruntExecutor.TaskingMessenger.ReadTaskingMessage()
   at GruntExecutor.Grunt.Execute(String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
Error
Loop Exception: System.Net.WebException The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GruntExecutor.HttpMessenger.Read()
   at GruntExecutor.TaskingMessenger.ReadTaskingMessage()
   at GruntExecutor.Grunt.Execute(String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
Loop Exception: System.Net.WebException The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GruntExecutor.HttpMessenger.Read()
   at GruntExecutor.TaskingMessenger.ReadTaskingMessage()
   at GruntExecutor.Grunt.Execute(String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
Loop Exception: System.Net.WebException The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GruntExecutor.HttpMessenger.Read()
   at GruntExecutor.TaskingMessenger.ReadTaskingMessage()
   at GruntExecutor.Grunt.Execute(String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
Loop Exception: System.Net.WebException The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GruntExecutor.HttpMessenger.Read()
   at GruntExecutor.TaskingMessenger.ReadTaskingMessage()
   at GruntExecutor.Grunt.Execute(String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
Loop Exception: System.Net.WebException The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GruntExecutor.HttpMessenger.Read()
   at GruntExecutor.TaskingMessenger.ReadTaskingMessage()
   at GruntExecutor.Grunt.Execute(String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
Loop Exception: System.Net.WebException The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GruntExecutor.HttpMessenger.Read()
   at GruntExecutor.TaskingMessenger.ReadTaskingMessage()
   at GruntExecutor.Grunt.Execute(String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
***

Error on terminal
***
Unhandled exception. System.ObjectDisposedException: Cannot process pending renders after the renderer has been disposed.                                             
Object name: 'Renderer'.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)                                          
   at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)                                                                              
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Covenant.Components.Grunts.GruntIndex.<>c__DisplayClass29_0.<OnEditGrunt>b__2() in /opt/Covenant/Covenant/Components/Grunts/GruntIndex.razor:line 96            
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<InvokeAsync>b__8_0(Object state)                                                  
--- End of stack trace from previous location where exception was thrown ---
   at Covenant.Components.Grunts.GruntIndex.OnEditGrunt(Object sender, Grunt grunt) in /opt/Covenant/Covenant/Components/Grunts/GruntIndex.razor:line 96              
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)                                                                   
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)                           
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
***

**Covenant Server Information:**
 - OS: Kali 2020
 - Docker or Native: Native

**Browser Information:**
 - Browser Chrome
 - Version  85.0.4183.83

**Target Information :**
 - OS: NA
 - Version NA

**Comment by cobbr** [comment]
Hey @0x01m4rv , if you have a custom Template that you think is breaking the server, please provide the Template so that I'll be able to test!

**Comment by 0x01m4rv** [comment]
In the default HTTP Template,

![image](https://user-images.githubusercontent.com/16485430/93000450-3a215400-f546-11ea-8016-10a88b381c6b.png)

Replace the three lines in the StagerCode with:

wc.UseDefaultCredentials = false;
wc.Proxy = new WebProxy
{
    Address = new Uri("http://proxyserver:port"),
    Credentials = new NetworkCredential
    {
        Domain = "DOMAIN",
        UserName = "user",
        Password = "password"
    }
}
 
![image](https://user-images.githubusercontent.com/16485430/93000491-72289700-f546-11ea-8f50-27d863c967c1.png)

And the three lines in the ExecutorCode with:

this.CovenantClient.UseDefaultCredentials = false;
this.CovenantClient.Proxy = new WebProxy
{
    Address = new Uri("http://proxyserver:port"),
    Credentials = new NetworkCredential
    {
        Domain = "DOMAIN",
        UserName = "user",
        Password = "password"
    }
};

**Comment by mpgn** [comment]
@0x01m4rv when I replace the code with your line I got this when generating a powershell launcher

![image](https://user-images.githubusercontent.com/5891788/94578729-5af0e580-0278-11eb-8b66-01b50fffe522.png)

**Comment by cobbr** [comment]
Hey @m4rvxpn , sorry for the delay in getting back with you. I can't seem to reproduce this. I've made these changes to a template, and everything seems to be working okay.

Are you sure this isn't a problem with your proxy?

**Comment by cobbr** [comment]
Closing due to inactivity. If you are still having this problem just let me know and we can re-open.
