### ISSUE TITLE
Upload fucntion failed

### ISSUE THREAD

**Issue by ChuanNegro** [cobbr/Covenant#298]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
I am trying to use a upload function.
After I choose the file and start task I got an error

System.UnauthorizedAccessException: Access to the path 'C:\Users\aecadmin\Desktop' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at Task.Execute(String FilePath, String FileContents)

Grunt is connected under this user aecadmin. So I do not understand why I am getting access denied.
AV is also disabled.

**Comment by nodauf** [comment]
Hi,
Can you create a file with the command shellcmd or is there also an access denied ?

**Comment by rasta-mouse** [comment]
@ChuanNegro you should also include the task parameters that you are using.

Remember that the `File.WriteAllBytes()` method in .NET requires the path to be absolute **and** should includes the filename and extension.  So your destination path should be `C:\Users\aecadmin\Desktop\file.whatever` and not just `C:\Users\aecadmin\Desktop`.

**Comment by ChuanNegro** [comment]
@rasta-mouse 
Thank you with absolute path it works. so the issue was between the chair and keyboard.

**Comment by cobbr** [comment]
To be fair, the output could definitely be a bit more clear about what is going on. I'll keep that as a note for future improvement.

Thanks for grabbing this one @rasta-mouse
