### ISSUE TITLE
[Bug|Error Request] Process terminated. Couldn't find a valid ICU package

### ISSUE THREAD

**Issue by memuratozturk** [cobbr/Covenant#367]
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.String.ToLowerInvariant()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetArch()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment..cctor()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
zsh: IOT instruction  /home/kali/.dotnet/dotnet run
                                                                                                                                  
I tried many times. I have searched and tested a lot on the internet but this error has not been fixed.
I keep getting this error.
Covenant c2 is not working.

**Comment by kymb0** [comment]
Are you by any chance using a new version of *nix? I am now getting this after spinning up a new kali box  2022.3 (previously on 2021.4a)

EDIT: Confirmed to be resolved for me by downgrading from kali 2022.3 to kali 2022.2
@cobbr @memuratozturk

**Comment by 0xBrAinsTorM** [comment]
Ran into the same issue on 2022.4. You can add the following parameter in the config file
/opt/Covenant/Covenant/bin/Debug/netcoreapp3.1/Covenant.runtimeconfig.json:

`"System.Globalization.Invariant": true`

So it looks like:

```
 {
   "runtimeOptions": {
     "tfm": "netcoreapp3.1",
     "framework": {
       "name": "Microsoft.AspNetCore.App",
       "version": "3.1.0"
     },
     "configProperties": {
       "System.GC.Server": true,
       "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false,
       "System.Globalization.Invariant": true
     }
   }
 }
```

*EDIT*
You can also add 

`<InvariantGlobalization>true</InvariantGlobalization>`

to the Covenant.csproj file
