### ISSUE TITLE
dotnet run not working 

### ISSUE THREAD

**Issue by HaidarX1** [cobbr/Covenant#380]
(kali㉿kali)-[~/Desktop/Covenant]
└─$ sudo dotnet run
[sudo] password for kali: 
Couldn't find a project to run. Ensure a project exists in /home/kali/Desktop/Covenant, or pass the path to the project using --project.

 can someone help me understand whats going on and how can fix this problem

**Comment by rasta-mouse** [comment]
Given the file structure, you probably want `/Desktop/Covenant/Covenant`.

**Comment by HaidarX1** [comment]
i did that the same error

**Comment by HaidarX1** [comment]
now its showing me this 

──(root㉿kali)-[/Covenant/Covenant]
└─#  dotnet run
You must install or update .NET to run this application.

App: /Covenant/Covenant/bin/Debug/netcoreapp3.1/Covenant
Architecture: x64
Framework: 'Microsoft.AspNetCore.App', version '3.1.0' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  6.0.8 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=kali.2022.4-x64

**Comment by checkymander** [comment]
You need to install .Net Core 3.1, seems the only one you have installed right now is .NET 6

**Comment by HaidarX1** [comment]
its showing this now 


Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication..ctor(McMaster.Extensions.CommandLineUtils.CommandLineApplication, McMaster.Extensions.CommandLineUtils.HelpText.IHelpTextGenerator, McMaster.Extensions.CommandLineUtils.Abstractions.CommandLineContext)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication..ctor()
   at Covenant.Program.Main(System.String[])

**Comment by rasta-mouse** [comment]
Follow the proper instructions to install .NET Core 3.1:  https://dotnet.microsoft.com/en-us/download/dotnet/3.1
Or you could try the Covenant dev branch which I believe is using .NET 5.

**Comment by not-sekiun** [comment]
> Follow the proper instructions to install .NET Core 3.1: https://dotnet.microsoft.com/en-us/download/dotnet/3.1 Or you could try the Covenant dev branch which I believe is using .NET 5.

Currently facing the same issue and apparently .NET core 3.1 is no longer supported on debian based systems. https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian#supported-distributions how am I supposed to install it then? The supplied binaries do not appear to work, following instructions here https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-3.1.426-linux-arm64-binaries upon installing the 3.1 SDK it is not registered by the dotnet utility itself

**Comment by vlados31999** [comment]
Friends 
This command solves this problem 

export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

**Comment by DramaKing19** [comment]
I'll try setting the environment variable, but I'm worried that I may need unicode and globalization support. I've followed all the .NET installation steps, but it still gives the error. Below is all of the installed dotnet packages.

dotnet-apphost-pack-3.1/bullseye,now 3.1.32-1 amd64 [installed,automatic]
dotnet-apphost-pack-6.0/bullseye,now 6.0.18-1 amd64 [installed,automatic]
dotnet-apphost-pack-7.0/bullseye,now 7.0.7-1 amd64 [installed,automatic]
dotnet-host/bullseye,now 7.0.7-1 amd64 [installed,automatic]
dotnet-hostfxr-3.1/bullseye,now 3.1.32-1 amd64 [installed,automatic]
dotnet-hostfxr-6.0/bullseye,now 6.0.18-1 amd64 [installed,automatic]
dotnet-hostfxr-7.0/bullseye,now 7.0.7-1 amd64 [installed,automatic]
dotnet-runtime-3.1/bullseye,now 3.1.32-1 amd64 [installed,automatic]
dotnet-runtime-6.0/bullseye,now 6.0.18-1 amd64 [installed,automatic]
dotnet-runtime-7.0/bullseye,now 7.0.7-1 amd64 [installed,automatic]
dotnet-runtime-deps-3.1/bullseye,now 3.1.32-1 amd64 [installed,automatic]
dotnet-runtime-deps-6.0/bullseye,now 6.0.18-1 amd64 [installed,automatic]
dotnet-runtime-deps-7.0/bullseye,now 7.0.7-1 amd64 [installed,automatic]
dotnet-sdk-3.1/bullseye,now 3.1.426-1 amd64 [installed]
dotnet-sdk-6.0/bullseye,now 6.0.410-1 amd64 [installed,automatic]
dotnet-sdk-7.0/bullseye,now 7.0.304-1 amd64 [installed]
dotnet-targeting-pack-3.1/bullseye,now 3.1.0-1 amd64 [installed,automatic]
dotnet-targeting-pack-6.0/bullseye,now 6.0.18-1 amd64 [installed,automatic]

**Comment by p4r7h** [comment]
is there any alternative to solve this issue ?

**Comment by DramaKing19** [comment]
> is there any alternative to solve this issue ?

Just using the workaround.
