### ISSUE TITLE
[Bug] Module ShellCmd  error "Could not load file or assembly"

### ISSUE THREAD

**Issue by mpgn** [cobbr/Covenant#66]
**Bug**

On the Interact tab, when I use the module ShellCmd I always got this error:

```
Task Exception: Could not load file or assembly '25088 bytes loaded from blo1dheg.1wq, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
   at System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, Boolean fSkipIntegrityCheck, SecurityContextSource securityContextSource)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly)
   at GruntExecutor.Grunt.TaskExecute(TaskingMessenger messenger, GruntTaskingMessage message)
```

Other module like Seatbelt or WhoAmI are working fine

**To Reproduce**
1. Go to a Grunt
2. Click on Interact
3. Use the module ShellCmd whoami

**Expected behavior**
The output of the command run by ShellCmd

**Screenshots**
![image](https://user-images.githubusercontent.com/5891788/65414685-7ec35500-ddf4-11e9-8558-1699f8244fa6.png)

**Covenant Server Information:**
 - OS: Windows 10 x64
 - Docker or Native: Native

**Browser Information:**
 - Browser Chrome
 - Version 77

**Target Information (System that implant is running on):**
 - OS: Windows 10 
 - Version 1903
 - NET Framework 4.8 installed

**Comment by mpgn** [comment]
Ok big mistake, I forgot to disabled defender ^^
